//dados
const deadpools = [
    {
        nome: "Deadpool Original",
        universo: "Marvel 616",
        habilidades: ["regeneração", "teletransporte", "fator de cura"],
        armas: ["espadas", "pistolas"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/Deadpool_616.png",
        tags: "original wade wilson"
    },
    {
        nome: "Deadpool Ultimate",
        universo: "Marvel Ultimate",
        habilidades: ["regeneração", "agilidade", "força sobre-humana"],
        armas: ["katanas", "pistolas"],
        grupo: "Carniceiros",
        imagem: "Imagens/Deadpool_Ultimate.png",
        tags: "ultimate malvado"
    },
    {
        nome: "Lady Deadpool",
        universo: "Terra-3010",
        habilidades: ["regeneração", "acrobacia", "mestre em artes marciais"],
        armas: ["katanas duplas", "pistolas"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/Lady_Deadpool.png",
        tags: "lady pool mulher"
    },
    {
        nome: "Deadpool X-Force",
        universo: "Marvel 616",
        habilidades: ["regeneração", "teletransporte", "fator de cura", "liderança"],
        armas: ["espadas", "pistolas", "teletransportador"],
        grupo: "X-Force",
        imagem: "Imagens/Deadpool_XForce.png"
    },
    {
        nome: "Deadpool Kid",
        universo: "Terra-10330",
        habilidades: ["regeneração", "teletransporte", "fator de cura"],
        armas: ["sabre de luz"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/Deadpool_Kid.png",
    },
    {
        nome: "HeadPool",
        universo: "Universo Alternativo",
        habilidades: ["imortalidade", "experiência em combate", "fator de cura"],
        armas: ["Faca"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/Headpool.png",
    },
    {
        nome: "Dogpool",
        universo: "Terra-103173",
        habilidades: ["Fator de cura", "superforça", "agilidade", "inteligência canina"],
        armas: ["Bolinhos de carne explosivos", "brinquedos com lâminas", "garras retráteis"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/Dogpool.png",
    },
    {
        nome: "Nicepool",
        universo: "Universo Alternativo",
        habilidades: ["resistência leve à morte por tiro", "ótimas habilidades"],
        armas: ["armas de ouro", "espadas"],
        grupo: "Independente",
        imagem: "Imagens/Nicepool.png",
    },
    {
        nome: "Babypool",
        universo: "Universo Alternativo",
        habilidades: ["Fator de cura acelerado", "Superforça bebê", "Resistência", "agilidade"],
        armas: ["armas de plástico", "pistolas d'água"],
        grupo: "Independente",
        imagem: "Imagens/Babypool.png",
    },
    {
        nome: "Deadpool Cowboy",
        universo: "Universo Alternativo",
        habilidades: ["Fator de cura acelerado", "Atirador", "Combate", "agilidade"],
        armas: ["revólver", "rifle", "faca"],
        grupo: "Independente",
        imagem: "Imagens/Deadpool_cowboy.png",
    },
    {
        nome: "Ronin-pool (Watari)",
        universo: "Universo Alternativo",
        habilidades: ["Fator de cura acelerado", "Mestre espadachim", "força", "agilidade"],
        armas: ["Katana", "shurikens", "arcos"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/Ronin.png",
    },
    {
        nome: "Deadpool 2099",
        universo: "Terra-16356",
        habilidades: ["Fator de cura acelerado", "adaptação", "aumento de força", "conhecimento tecnológico"],
        armas: ["Katana cibernética", "pistolas inteligentes", "Implantes cibernéticos"],
        grupo: "X-men 2099",
        imagem: "Imagens/Deadpool2099.png",
    },
    {
        nome: "Deadpool da Era de Ouro",
        universo: "Terra-TRN245",
        habilidades: ["Fator de cura acelerado", "força", "combatente"],
        armas: ["Dois sabres"],
        grupo: "Deadpool Corps",
        imagem: "Imagens/GADeadpool.png",
    },
    {
        nome: "Zenpool",
        universo: "Terra-616",
        habilidades: ["regeneração", "teletransporte", "fator de cura"],
        armas: ["Bastão de madeira"],
        grupo: "X-Men",
        imagem: "Imagens/Zenpool.png",
    },
    {
        nome: "Lego Deadpool",
        universo: "Terra-13122",
        habilidades: ["regeneração", "teletransporte", "fator de cura", "destruição"],
        armas: ["Katanas de lego", "pistolas de lego"],
        grupo: "Independente",
        imagem: "Imagens/Lego_Deadpool.png",
    },
  ];